package tests.deployment;

public enum PropKeys {
	POSTS_REST_SERVICE_MAINCLASS, POSTS_REST_SERVICE_PORT, POSTS_SOAP_SERVICE_MAINCLASS, POSTS_SOAP_SERVICE_PORT, PROFILES_REST_SERVICE_MAINCLASS, PROFILES_REST_SERVICE_PORT, PROFILES_SOAP_SERVICE_MAINCLASS, PROFILES_SOAP_SERVICE_PORT,

	MEDIASTORAGE_REST_SERVICE_MAINCLASS, MEDIASTORAGE_REST_SERVICE_PORT, DISCOVERY_MULTICAST_ADDRESS, USES_KAFKA_BOOL;

	@Override
	public String toString() {
		return super.toString().replaceAll("_", "-").toLowerCase();
	}
}
